### ISSUE TITLE
Summary doesn't work

### ISSUE THREAD

**Issue by Bearzooka** [SAP/power-monitoring-tool-for-macos#1]
Hey SAP team, thanks for this awesome tool, it's a great idea.

Whenever I run `/Applications/Power\ Monitor.app/Contents/MacOS/Power\ Monitor --noGUI --journal --summarize w` (or `m` or `y` as the timeframe) the application seems to hang and I never get a result.

At first I thought I might need to wait for 7 days to have enough info for a weekly summary, but after more than a week I still have this behavior.

**Comment by Tschensche** [comment]
I'm having the same problem on macOS Sonoma 14.4.1. The main window only show the current System wattage, but for all the other values (average, peak and daily power consumption). 

It worked fine when I first installed the application. It seems that the error occurs after the first reboot.

**Comment by Tschensche** [comment]
issue is fixed when updating to Sonoma 14.5 (tested version of the devs) and reinstalling the app by uninstalling completely as guided in the README.md and reinstalling it.

**Comment by Bearzooka** [comment]
Thanks for the info @Tschensche.
As it turns out, deleting `/Users/Shared/Power Monitor/journal.plist` was just enough to get the summary running; however, now that I don't have a journal, the summary is empty and I need to wait for some info to gather.

If I bring back the old journal file, the summary is broken again, which makes me think that the file itself has some sort of error.

**Comment by mthielemann** [comment]
@Bearzooka Could you please send me the journal plist so I can have a look at it? Thanks.

**Comment by Bearzooka** [comment]
Thanks @mthielemann, here it goes.

[journal.plist.zip](https://github.com/user-attachments/files/15805888/journal.plist.zip)

**Comment by mthielemann** [comment]
@Bearzooka This will be fixed in version 1.2.2. Thanks for reporting this issue.
