### ISSUE TITLE
Add the Power Input of the current Charger

### ISSUE THREAD

**Issue by redbasecap** [SAP/power-monitoring-tool-for-macos#2]
Hardware-Konfiguration:

  USV installiert:	Nein

Informationen zum Ladegerät:

  Ladegerät angeschlossen:	Ja
  ID:	0x0000
  Leistung (W):	60
  Familie:	0xe000400a
  Batterie wird geladen:	Nein

Ereignisse zur Stromversorgung:

I see often that over the usb c you get very low power input it would be very nice to see this in your tool.

**Comment by mthielemann** [comment]
I think that there are already quite a few tools that can display this value. Could you please explain why you think it would be useful to display this value in Power Monitor? Thank you.

**Comment by redbasecap** [comment]
I realized that there are some batterie problems when people are using a very bad charger so it help identify this problem directly :)

Lieber Gruss

Nicola Spieser
Nachricht von Marc Thielemann ***@***.***> am 8. Okt. 2024, 17:29 +0200:

**Comment by mthielemann** [comment]
Ok. I could add something like a power info section to the Console window. This could provide some basic information about the power supply and battery.

**Comment by mthielemann** [comment]
@redbasecap Would this help?
<img width="1402" alt="Screenshot 2024-10-10 at 13 13 50" src="https://github.com/user-attachments/assets/34da4074-1970-43b4-8b23-a055dfc50e79">

**Comment by redbasecap** [comment]
Yes exactly in your example the 94 Watts.

Thx

Best Regards Nick
Nachricht von Marc Thielemann ***@***.***> am 10. Okt. 2024, 13:15 +0200:

**Comment by mthielemann** [comment]
Ok. We‘ll release version 1.2.3 shortly which will include this feature.

**Comment by redbasecap** [comment]
Amazing Thx!

BG

Nick
Am 10. Okt. 2024, 19:21 +0200 schrieb Marc Thielemann ***@***.***>:

**Comment by mthielemann** [comment]
@redbasecap Version 1.2.3 has just been released.
