### ISSUE TITLE
Support macOS 15.x

### ISSUE THREAD

**Issue by elijaholmos** [SAP/power-monitoring-tool-for-macos#3]
With the public release of macOS 15 (Sequoia), are there any plans to introduce compatibility with this tool?

**Comment by mthielemann** [comment]
What does not work on your end? We use it on over 20.000 Macs running macOS 15 without any issues.

**Comment by DevliegereM** [comment]
for some reason the `.mobileconfig` is applied but does not change the settings inside the app.

**Comment by mthielemann** [comment]
Could you please provide your profile? Tested this on my end and everything works as expected. Thanks.
