### ISSUE TITLE
I couldn't be able to run it properly

### ISSUE THREAD

**Issue by pst1998** [SAP/power-monitoring-tool-for-macos#4]
I didn't get the problem yet. but in my case it doesn't show watt values, ı tried different compatible versions with macOS Ventura 13.7. but it doesn't work. here is some footage, ı don't think but could it be with the intel based MacBook?
<img width="460" alt="Ekran Resmi 2024-10-16 07 36 49" src="https://github.com/user-attachments/assets/36ae46a9-c636-4977-815b-98a54ed4cd3d">
<img width="298" alt="Ekran Resmi 2024-10-16 07 37 44" src="https://github.com/user-attachments/assets/cae90bf6-7709-4a31-bf2d-10939381b355">
<img width="240" alt="Ekran Resmi 2024-10-16 07 38 11" src="https://github.com/user-attachments/assets/b988caf5-8f66-4dc3-a152-1f0abb0bb5b4">

**Comment by mthielemann** [comment]
Unfortunately not all Mac models provide power information and in this case you see a power value of 0 Watts.

**Comment by pst1998** [comment]
> Unfortunately not all Mac models provide power information and in this case you see a power value of 0 Watts.

thanks for the answer I taught so
