### ISSUE TITLE
All readings are zero

### ISSUE THREAD

**Issue by ssummer** [SAP/power-monitoring-tool-for-macos#5]
I installed yesterday on my Intel MacBook Pro 2017, but it shows zeros for all readings however it does show graphs with different length bars and gaps, but the hover over also shows zeros. The only values it shows as non-zero are the time range and power nap period, currently 18 and 4 hours respectively.
I'm on macos Ventura 13.7.1
Screenshot attached.

[PowerMonitor-zeros.pdf](https://github.com/user-attachments/files/17876803/PowerMonitor-zeros.pdf)

**Comment by mthielemann** [comment]
Thank you for reporting this. Unfortunately, if the app shows a zero power value, it means that your hardware is not providing that information.
