### ISSUE TITLE
Does it include power wasted by charger?

### ISSUE THREAD

**Issue by RogerRamjet-AJ** [SAP/power-monitoring-tool-for-macos#6]
Not an issue, a question.

I was expecting my idle power consumption to be about 1.7 watts, because when my MacBook Air M1 is unplugged, 'Battery Health 2' app always settles down to that, at a given screen brightness.

I just used your tool to measure idle consumption when plugged in (and not charging) and I get about 2.5 watts, consistently.

But when I unplug it, both your app and BH2 agree, it is indeed about 1.7 watts.

I'm wondering if the MacBook itself starts using a bit more power when plugged in vs being on battery. I've set it up to not change screen brightness, and never change in/out of low power mode automatically. So not sure what the extra energy is being used for.

I'm wondering if your app cunningly also measures or estimates the energy being used and wasted by the charger itself?

Thanks!

**Comment by mthielemann** [comment]
MacBook typically reduces power consumption when running on battery, especially when running on battery in low-power mode. So the behavior you describe is expected. Power Monitor does not know about the charger, so it does not measure the power consumption of the charger.
